1.7.0.1 version of scripts

diff --git a/bart b/bart
--- a/bart
+++ b/bart
@@ -1,11 +1,13 @@
 #!/sbin/sh
-VER="1.0.1"
+VER="1.3.1"
 MYFOLDER="bart"
 SDCARD="/sdcard"
 EXTPART="/system/sd"
+CACHEPART="/cache"
 NANDSH="nandroid-mobile.sh"
 NANDLOG="nandroid.log"
-RECOVERY="foo"
+CONFIGFILE="/system/sd/bart.config"
+
 alias _GREP_="busybox grep"
 alias _AWK_="busybox awk"
 alias _MOUNT_="busybox mount"
@@ -29,6 +31,7 @@ myecho=":"
 ni=0
 reboot=0
 shutdown=0
+docache=1
 
 do_exit()
 {
@@ -58,6 +61,7 @@ print_usage()
 	echo "	  -n --nandroid_only, use with -r or -s"
 	echo "          -v --version"
 	echo "	  --verbose, verbose output during nandroid"
+	echo "	  --nocache, ignore the cache partition"
 	echo "	  --norecovery, ignore recovery partition"
 	echo "	  --noboot, ignore boot partition"
 	echo "	  --nodata, ignore data partition"
@@ -126,12 +130,68 @@ read_rom()
 	fi
 }
 
+# make sure /system/sd and /sdcard are mounted
+
+$myecho "check for /system/sd or /sd-etc"
+
+if [ -e "/sd-ext" ]
+then
+	EXTPART="/sd-ext"
+	CONFIGFILE="/sd-ext/bart.config"
+else
+	if [ -e "/system/sd" ]
+	then
+		EXTPART="/system/sd"
+		CONFIGFILE="/sd-ext/bart.config"
+	fi
+fi
+
+$myecho "checking mount points..."
+for i in ${SDCARD} ${EXTPART}
+do
+	if [ "$i" == ${EXTPART} ] && [ $nandroid_only -eq 1 ]
+	then
+		$myecho "nandroid_only chosed ext partition not needed..."
+	else
+		$myecho "checking whether $i is mounted..."
+		mounted=`_GREP_ $i /proc/mounts | _AWK_ '{print $2}'`
+		if [ "$mounted" != "$i" ]
+		then
+			$myecho "$i is not mounted.  mounting $i now..."
+			# not mounted, mount it
+			_MOUNT_ $i
+			if [ $? -ne 0 ]
+			then
+				echo "Unable to mount $i ..."
+				echo ""
+				do_exit 5
+			fi
+		fi
+	$myecho "$i is mounted..."
+	fi
+done
+
+
 # args processing
 if [ $# -lt 1 ]
 then
 	print_usage
 	exit 1
 fi
+
+
+
+# check for config file
+if [ -f $CONFIGFILE ]
+then
+	$myecho "found $CONFIGFILE"
+
+	. $CONFIGFILE
+
+fi
+
+
+# get args from command line
 while [ -n "$1" ]
 do
 	case "$1" in
@@ -177,6 +237,11 @@ do
                 shutdown=1
                 shift
                 ;;
+	--nocache)
+		$myecho "setting cache option..."
+		docache=0
+		shift
+		;;
 	-a|--app_s)
 		$myecho "setting app_s option..."
 		app_s=1
@@ -281,31 +346,6 @@ do
 	esac
 done
 
-# make sure /system/sd and /sdcard are mounted
-$myecho "checking mount points..."
-for i in ${SDCARD} ${EXTPART}
-do
-	if [ "$i" == ${EXTPART} ] && [ $nandroid_only -eq 1 ]
-	then
-		$myecho "nandroid_only chosed ext partition not needed..."
-	else
-		$myecho "checking whether $i is mounted..."
-		mounted=`_GREP_ $i /proc/mounts | _AWK_ '{print $2}'`
-		if [ "$mounted" != "$i" ]
-		then
-			$myecho "$i is not mounted.  mounting $i now..."
-			# not mounted, mount it
-			_MOUNT_ $i
-			if [ $? -ne 0 ]
-			then
-				echo "Unable to mount $i ..."
-				echo ""
-				do_exit 5
-			fi
-		fi
-	$myecho "$i is mounted..."
-	fi
-done
 
 myhome="${SDCARD}/${MYFOLDER}"
 rompath="${myhome}/${romname}"
@@ -322,7 +362,7 @@ case "$cmd" in
 		fi
 		rompath="${myhome}/${romname}"
 		nandfolder="${rompath}/nandroid"
-
+		
 		if [ $nandroid_only -eq 1 ]
 		then
 			echo ""
@@ -454,6 +494,63 @@ case "$cmd" in
 			echo "ROM ${romname} not found at ${myhome}..."
 			echo ""
 			do_exit 30
+		fi
+
+		if [ $docache -eq 1 ]
+		then
+			compressed=0
+			$myecho "checking for cache partition backup..."
+			if [ -e "${rompath}/cache-backup.tar.gz" ]
+			then
+				$myecho "compressed cache-backup found..."
+				compressed=1
+			else
+				if [ ! -e "${rompath}/cache-backup.tar" ]
+				then
+					echo ""
+					echo "cache-backup not fount for ROM ${romname}."
+					echo ""
+					do_exit 29
+				fi
+				$myecho "uncompressed cache-backup found..."
+			fi
+			#proceed with restoring cache
+			echo "Cleaning up /cache..."
+			cd ${CACHEPART}
+			_RM_ -rf `_LS_ -d * | grep -v -e "^recovery" -e	"^lost+found"  2>&1` > /dev/null 2>&1
+
+			if [ $compressed -eq 1 ]
+			then
+				echo "Restoring compressed cache-backup in ${CACHEPART} ..."
+				cd ${CACHEPART}
+				gzip -c -d "${rompath}/cache-backup.tar.gz" | _TAR_ xpf -
+				if [ $? -ne 0 ]
+				then
+					echo ""
+					echo "Error occurred during restoration of cache data..."
+					echo "tar/gzip operation failed."
+					echo "Do you have enough space on the /sdcard?"
+					echo ""
+					do_exit 28
+				fi
+				cd /
+			else
+				echo "Restoring cache-backup in ${CACHEPART} ..."
+				cd ${CACHEPART}
+				_TAR_ xpf "${rompath}/cache-backup.tar"
+				if [ $? -ne 0 ]
+				then
+					echo ""
+					echo "Error occurred during restoration of cache-backup ..."
+					echo "tar operation failed."
+					echo "Do you have enough space on the /sdcard?"
+					echo ""
+					do_exit 27
+				fi
+				cd /
+			fi
+	
+
 		fi
 
 		if [ $nandroid_only -eq 0 ]
@@ -606,6 +703,23 @@ case "$cmd" in
 
 		if [ $compressed -eq 1 ]
 		then
+			if [ $docache -eq 1 ]
+			then
+				$myecho "storing cache..."
+				cd ${CACHEPART}
+				_TAR_ cpf - `_LS_ -d * | grep -v -e "^lost+found" -e "^recovery" 2>/dev/null` | gzip -1 > "${rompath}/cache-backup.tar.gz"
+				if [ $? -ne 0 ]
+				then
+					echo ""
+					echo "Error occurred during storing of cache data..."
+					echo "tar/gzip operation failed."
+					echo "Do you have enough space on the /sdcard?"
+					echo ""
+					do_exit 15
+				fi
+
+			fi
+
 			if [ $nandroid_only -eq 0 ]
 			then
 				# store the apps partition data
@@ -661,6 +775,24 @@ case "$cmd" in
 				fi
 			fi
 		else
+			if [ $docache -eq 1 ]
+			then
+				$myecho "storing cache..."
+				cd ${CACHEPART}
+				_TAR_ cpf "${rompath}/cache-backup.tar" `_LS_ -d * | grep -v -e "^lost+found" -e "^recovery" 2>/dev/null`
+				if [ $? -ne 0 ]
+				then
+					echo ""
+					echo "Error occurred during storing of cache data..."
+					echo "tar/gzip operation failed."
+					echo "Do you have enough space on the /sdcard?"
+					echo ""
+					do_exit 15
+				fi
+
+			fi
+
+
 			if [ $nandroid_only -eq 0 ]
 			then
 				# store the apps partition data
